//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResultManagement
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ResultManagementDbEntities : DbContext
    {
        public ResultManagementDbEntities()
            : base("name=ResultManagementDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblClass> tblClass { get; set; }
        public virtual DbSet<tblExamType> tblExamType { get; set; }
        public virtual DbSet<tblResultDetails> tblResultDetails { get; set; }
        public virtual DbSet<tblResults> tblResults { get; set; }
        public virtual DbSet<tblStudents> tblStudents { get; set; }
        public virtual DbSet<tblClassSubject> tblClassSubject { get; set; }
        public virtual DbSet<tblSubjects> tblSubjects { get; set; }
    }
}
