//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResultManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblResults
    {
        public int ResultId { get; set; }
        public Nullable<int> StudentId { get; set; }
        public Nullable<int> ClassId { get; set; }
        public Nullable<int> ExamTypeId { get; set; }
        public string Result { get; set; }
    
        public virtual tblClass tblClass { get; set; }
        public virtual tblExamType tblExamType { get; set; }
        public virtual tblResults tblResults1 { get; set; }
        public virtual tblResults tblResults2 { get; set; }
        public virtual tblStudents tblStudents { get; set; }
    }
}
