//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResultManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblResultDetails
    {
        public int DetailId { get; set; }
        public Nullable<int> ResultId { get; set; }
        public Nullable<int> SubjectId { get; set; }
        public string Marks { get; set; }
    
        public virtual tblSubjects tblSubjects { get; set; }
    }
}
